# Generated by Django 4.2.7 on 2024-03-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
