# Generated by Django 4.2.7 on 2024-03-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='geodata',
            field=models.FileField(blank=True, null=True, upload_to='lots_geodata'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='geodata',
            field=models.FileField(blank=True, null=True, upload_to='parcel_geodata'),
        ),
    ]
