# Generated by Django 4.2.7 on 2024-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
