# Generated by Django 4.2.7 on 2024-03-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_inferencejob_latitude_inferencejob_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failure', 'Failure')], default='pending'),
        ),
    ]
